=== kamarz01/ZagAPI-Framework/src/main/resources/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "API Definition Schema",
  "description": "Defines the schema used to validate an api definition",
  "type": "object",
  "properties": {
    "name": {
      "description": "API/Service name",
      "type": "string"
    },
    "description": {
      "description": "API/Service description",
      "type": "string"
    },
    "proxy": {
      "description": "API/Service proxy info",
      "type": "object",
      "properties": {
        "useProxy": {
          "description": "Enable/Disable the use of proxy",
          "type": "boolean"
        },
        "host": {
          "description": "Proxy host name",
          "type": "string"
        },
        "port": {
          "description": "Proxy port",
          "type": "string"
        },
        "username": {
          "description": "Proxy auth username if required",
          "type": "string"
        },
        "password": {
          "description": "Proxy auth password if required",
          "type": "string"
        }
      }
    },
    "requests": {
      "description": "API/Service request list",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "description": "API Request id",
            "type": "string"
          },
          "endPoint": {
            "description": "API Endpoint",
            "type": "string"
          },
          "method": {
            "description": "API Http Method",
            "type": "string",
            "enum": ["GET","POST","PATCH","DELETE","PUT","OPTIONS"]
          },
          "requestData": {
            "description": "API request data",
            "type": "object",
            "properties": {
              "queryParameters": {
                "description": "API Request Query Parameters",
                "type": "object"
              },
              "headers": {
                "description": "API Request headers",
                "type": "object"
              },
              "body": {
                "description": "API Request body",
                "type": "object"
              }
            }
          }
        },
        "required": ["id","endPoint","method","requestData"]
      }
    }
  },
  "required": ["name", "description", "proxy", "requests"]
}

=== kamarz01/ZagAPI-Framework/src/test/resources/testAPI-form.json
{
  "name": "API/Service Name",
  "description": "This is a service/API description.",
  "proxy": {
    "useProxy": false,
    "host": "host",
    "port": "8080",
    "username": "user",
    "password": "pass"
  },
  "requests": [
    {
      "id": "request-form",
      "endPoint": "get?id=value&user&key=value",
      "method": "GET",
      "requestData": {
        "queryParameters": {
          "key": "value",
          "key2": "value2"
        },
        "formParameters": {
          "formKey": "formValue",
          "formKey2": "formValue2"
        },
        "headers": {
          "header1": "header-value-1",
          "header2": "header-value-2"
        }
      }
    }
  ]
}

=== kamarz01/ZagAPI-Framework/src/test/resources/testAPI.json
{
  "name": "API/Service Name",
  "description": "This is a service/API description.",
  "proxy": {
    "useProxy": false,
    "host": "91.224.62.194",
    "port": "8080",
    "username": "az",
    "password": "xz"
  },
  "requests": [
    {
      "id": "request-1",
      "endPoint": "{{ENV::endpoint}}",
      "method": "POST",
      "requestData": {
        "queryParameters": {
          "key": "value",
          "key2": "value2"
        },
        "headers": {
          "header1": "{{ENV::env1}}",
          "header2": "{{ENV::env2}}"
        },
        "body": {
          "test": {
            "name": "Kamar",
            "phone": "123456"
          },
          "array": [
            {
              "t1": "{{ENV::env3}}"
            }
          ]
        }
      }
    }
  ]
}
